# Generated by Django 5.1.7 on 2025-05-28 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0021_complaint_admin_response_complaint_responded_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="client_feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="feedback_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="resolution_rating",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("AWAITING_USER_RESPONSE", "Awaiting User Response"),
                    ("RESOLVED", "Resolved"),
                    ("NEEDS_FURTHER_ACTION", "Needs Further Action"),
                    ("CLOSED", "Closed"),
                ],
                default="PENDING",
                max_length=100,
            ),
        ),
    ]
