# Generated by Django 5.1.7 on 2025-05-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0022_complaint_client_feedback_complaint_feedback_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Upload project requirements or reference documents",
                null=True,
                upload_to="job_attachments/",
            ),
        ),
    ]
