# Generated by Django 5.1.7 on 2025-05-30 05:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0023_job_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="attachment",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Upload project requirements or reference documents",
                max_length=255,
                null=True,
                verbose_name="job_attachment",
            ),
        ),
        migrations.AlterField(
            model_name="professionalprofile",
            name="verify_doc",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Upload verification document (PDF, DOC, etc.)",
                max_length=255,
                null=True,
                verbose_name="verification_document",
            ),
        ),
    ]
